# Generated by Django 5.2.3 on 2025-08-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.FloatField(default=0.005)),
                ('grid_rows', models.IntegerField(default=3)),
                ('grid_cols', models.IntegerField(default=3)),
                ('gap_x', models.IntegerField(default=2220)),
                ('gap_y', models.IntegerField(default=3100)),
                ('x_steps', models.IntegerField(default=505)),
                ('y_steps', models.IntegerField(default=610)),
            ],
            options={
                'verbose_name': 'Scan Configuration',
                'verbose_name_plural': 'Scan Configuration',
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site_number', models.CharField(max_length=4)),
                ('sample_type', models.CharField(max_length=50)),
                ('transect', models.CharField(max_length=10)),
                ('run_number', models.IntegerField(default=1)),
                ('retake', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this scan setting', max_length=100, unique=True)),
                ('sample_1', models.CharField(max_length=100)),
                ('sample_2', models.CharField(max_length=100)),
                ('sample_3', models.CharField(max_length=100)),
                ('sample_4', models.CharField(max_length=100)),
                ('sample_5', models.CharField(max_length=100)),
                ('sample_6', models.CharField(max_length=100)),
                ('delay', models.FloatField(default=0.005)),
                ('grid_rows', models.IntegerField(default=3)),
                ('grid_cols', models.IntegerField(default=3)),
                ('gap_x', models.IntegerField(default=2220)),
                ('gap_y', models.IntegerField(default=3100)),
                ('x_steps', models.IntegerField(default=505)),
                ('y_steps', models.IntegerField(default=610)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
