# Generated by Django 5.2.6 on 2025-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_scanrecord_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnstitchedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_folder', models.CharField(help_text='Name of the run folder (e.g., run_001)', max_length=200, unique=True)),
                ('run_path', models.CharField(help_text='Full path to the run folder', max_length=500)),
                ('total_subfolders', models.IntegerField(default=0, help_text='Total number of subfolders in this run')),
                ('stitched_subfolders', models.IntegerField(default=0, help_text='Number of subfolders that have been successfully stitched')),
                ('stitched_folder_names', models.TextField(blank=True, default='', help_text='JSON list of stitched folder names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False, help_text='True when 6 or more subfolders have been successfully stitched')),
            ],
            options={
                'verbose_name': 'Unstitched Run',
                'verbose_name_plural': 'Unstitched Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
