# Generated by Django 5.2.6 on 2025-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_unstitchedrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='is_splitted',
            field=models.BooleanField(default=False, help_text='True if this sample was split (duplicate)'),
        ),
    ]
