# Generated by Django 5.2.10 on 2026-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_scanrecord_is_splitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=4)),
                ('sample_type', models.CharField(max_length=50)),
                ('transect', models.CharField(max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rescan Request',
                'verbose_name_plural': 'Rescan Requests',
                'ordering': ['-requested_at'],
                'unique_together': {('site_number', 'sample_type', 'transect')},
            },
        ),
    ]
