# Generated by Django 5.2.10 on 2026-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_rescanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='stitched',
            field=models.BooleanField(default=False, help_text='True if this sample has been successfully stitched'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='stitcher_retake',
            field=models.BooleanField(default=False, help_text='True if this sample was requested for retake by Stitcher app'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='retake',
            field=models.BooleanField(default=False, help_text='True if this sample was retaken on Shimsy (Shimsy-Retake)'),
        ),
    ]
