"""
Django settings for cnccontroller project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from shimsy_secrets import get_config

_local = get_config()

CONTROLLER_DIR = BASE_DIR / "controller"

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_ROOT = "/app/media/"
MEDIA_URL = "/media/"
  
SECRET_KEY = _local["django_secret_key"]

DEBUG = bool(_local.get("debug", True))

ALLOWED_HOSTS = list(_local.get("allowed_hosts") or ["localhost", "127.0.0.1"])


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'controller'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cnccontroller.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'controller.context_processors.shimsy_frontend',
            ],
        },
    },
]

WSGI_APPLICATION = 'cnccontroller.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STITCHER_URL = _local.get("stitcher_url") or ""
STITCHER_JS_URL = _local.get("stitcher_js_url") or ""
STITCHER_JS_URL_ZEROTIER = STITCHER_JS_URL
STITCHER_FORM_URL_BASE = (_local.get("stitcher_form_url_base") or "").rstrip("/")
ERROR_MSG_KEY = 'ERROR'

_scans_base = _local.get("shimsy_scans_base") or os.environ.get("SHIMSY_SCANS_BASE", "")
SHIMSY_SCANS_BASE = _scans_base or str(BASE_DIR / "shimsy_scans")
SHIMSY_STAGING = _local.get("shimsy_staging") or os.environ.get("SHIMSY_STAGING", "")
SHIMSY_TEMP_BASE = _local.get("shimsy_temp_base") or ""
SHIMSY_REPO_HOME = _local.get("repo_home") or str(BASE_DIR)
NAS_IP = _local.get("nas_ip") or ""
NAS_EXPORT = _local.get("nas_export") or "/pool1/srv/shimsy/shimsy_scans"